### ISSUE TITLE
Worlds Folder

### ISSUE THREAD

**Issue by solvedDev** [bridge-core/project-config-standard#2]
## Motivation:
While working on larger Minecraft projects, teams often work with multiple different worlds at the same time. At the moment, it is only possible to define a single world template inside of the project config.

## Proposal:
Add a new `worlds` field of type `string[]` to the project config which defines a list of glob patterns pointing to folders storing Minecraft worlds. Glob patterns may not end with "**" to avoid ambiguity. If implementors encounter such an invalid glob pattern upon parsing, a warning should be raised and the glob pattern should be ignored.

```json
{
  "name": "My Project",
  "packs": {
    "behaviorPack": "./packs/BP"
  },
  "worlds": ["./worlds/*"]
}
```

```json
{
  "name": "My Project",
  "packs": {
    "behaviorPack": "./packs/BP"
  },
  "worlds": ["./worlds/1", "./worlds/other/*"]
}
```

**Comment by SirLich** [comment]
I think the `mincraft` in `minecraftWorlds` might be a little redundant.

**Comment by evilguy50** [comment]
Should also be an array if the intention is to support multiple

**Comment by solvedDev** [comment]
Good call, "worlds" is more inline with "packs". 
My current thinking is that all worlds of a project would be stored within the same folder so an array variant wouldn't be strictly necessary imo

**Comment by Nusiq** [comment]
I think it only makes sense as an array. I already know that I would never use multiple worlds in a project but it's highly probable that I would use a single world which would be contained in a folder with other worlds that I don't need.

This is because I typically work directly in `.../com.mojang/minecraftWorlds` folder where the world is a Git repository. When I work with Regolith I put the regolith project in a subfolder of the wrold: `.../com.mojang/minecraftWorlds/<world-name>/regolith`, so for me the only world path on the list would be `..`.

**Comment by solvedDev** [comment]
This is an interesting perspective. I wonder whether we can somehow find a solution that better supports the different ways people work with Minecraft worlds.

**Comment by Nusiq** [comment]
![image](https://user-images.githubusercontent.com/34062025/157341596-7f9f32a2-f2b0-4a0b-b9e3-90d74d88184b.png)

**Comment by solvedDev** [comment]
Main proposal is now updated to include the recent ideas
